[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Ryan Hofer <r.h.hofer@gmail.com>"]

[lib]
name = "adventofcode2018"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2"
scan_fmt = "0.1.3"
intrusive-collections = "0.6"